### ISSUE TITLE
Add image to page "Understanding æternity"

### ISSUE THREAD

**Issue by DanMercurius** [aeternity/wiki#3]
please add the following image 
![ae101_blockchainorganism](https://cloud.githubusercontent.com/assets/28238969/26213626/0a9ab6b2-3bfa-11e7-8591-9f0f9896753d.png)
to the repository. I want to use it on the page to show the vision of æternity

**Comment by zack-bitcoin** [comment]
The oracles are below state channels.
Using ethereum as an example for smart contracts is no good, because our smart contracts can't do ethereum's most important application.
We should really call this row "financial derivatives" instead of "smart contracts", and have the example be "options".

It should be possible for you to add pictures, ill try to figure out how.

**Comment by zack-bitcoin** [comment]
I think if you go to the main page https://github.com/aeternity/wiki
Then click the button that says "upload files"

**Comment by DanMercurius** [comment]
image added https://github.com/aeternity/wiki/blob/master/AE101_BlockchainOrganism.png
